################### DataSource Configuration ##########################
spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://rm-2ze378rwv37etj956bo.pg.rds.aliyuncs.com:3432/postgres
    username: postgres
    password: Cateye@2018
  table:
    china_city_polygon: s_ods_city_simplify
    t_tilemapservice: t_tilemapservice
    t_tilemap: t_tilemap
    t_tileset: t_tileset
    t_log: t_log
################### Service Configuration ##########################
service:
  mapserver: localhost:8080
  geoserver: localhost:8888
  tiledata: F:/BaiduNetdiskDownload
################### OSS Configuration ##########################
oss:
  accessKeyId: LTAIelgAxlE5sJMB
  accessKeySecret: RE0tSBGvQjD7EkCNILYfSqC7JGArn3
  endpoint: oss-cn-beijing.aliyuncs.com
  bucket: cateye-tile
################### DEM Data ##########################
dem:
  gujiao: e:/data/gujiao.tif
  jingzhuang: e:/data/jzhdem_7m.tif