################### DataSource Configuration ##########################
spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://rm-2ze378rwv37etj956bo.pg.rds.aliyuncs.com:3432/postgres
    username: postgres
    password: Cateye@2018
################### Service Configuration ##########################
service:
  mapserver: 39.107.104.63:8080
  geoserver: localhost:8888
  tiledata: /opt/tiledata
################### OSS Configuration ##########################
oss:
  accessKeyId: LTAIelgAxlE5sJMB
  accessKeySecret: RE0tSBGvQjD7EkCNILYfSqC7JGArn3
  endpoint: oss-cn-beijing-internal.aliyuncs.com