################### DataSource Configuration ##########################
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://111.202.109.210:5432/postgres
    username: postgres
    password: Cateye@2018
    hikari:
      pool-name: CatHikariCP
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 15
  table:
    china_city_polygon: s_ods_city_simplify
    t_tilemapservice: t_tilemapservice
    t_tilemap: t_tilemap
    t_tileset: t_tileset
    t_log: t_log
    t_project: t_project
    t_dataset: t_dataset
################### Service Configuration ##########################
service:
  mapserver: localhost:8080
  geoserver: localhost:8888
  tiledata: F:/BaiduNetdiskDownload
################### OSS Configuration ##########################
oss:
  accessKeyId: LTAIelgAxlE5sJMB
  accessKeySecret: RE0tSBGvQjD7EkCNILYfSqC7JGArn3
  endpoint: oss-cn-beijing.aliyuncs.com
  bucket: cateye-tile
################### DEM Data ##########################
dem:
  gujiao: e:/data/gujiao.tif
  jingzhuang: e:/data/jzhdem_7m.tif