server:
  port: 8080
# Spring properties
logging:
  level:
    com.lbi.tile: INFO
################### DataSource Configuration ##########################
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres